# 회원가입
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "test1@example.com",
  "nickName": "김회원",
  "password": "12341234"
}

### 로그인
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "12341234"
}

### 토큰 재발급 
POST http://localhost:3000/token/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc1MTI5NDAyMSwiZXhwIjoxNzUxMjk3NjIxfQ.m6wz5Be9UwVQdou1J3tUb7miIx0jpsAD8f3dDK7sa0k

###
 http://localhost:3000/uploads/1746979915826.png


###
GET http://localhost:3000

### 유저 정보 조회
GET http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc1MjE1NzYyNSwiZXhwIjoxNzUyMTU4NTI1fQ.ORnxDUxHstgcJVCgMhe3UISd5_YQp_7X4BpcM-2xP-Q

### 로그아웃
POST http://localhost:3000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2MjE1OTgyMywiZXhwIjoxNzYyMTYwNzIzfQ.7qGwvQAbTcHWbxtOL6vVIdq6QS-phjUvaRYH5-Fr3HY
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2MjE1OTgyMywiZXhwIjoxNzYyMTYzNDIzfQ.-2km8sbarczYuI-sRIpoVwPPlNtodYmM63g20huaGN8